# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rename.ui'
#
# Created: Sun Nov 21 16:52:33 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mainWidget(object):
    def setupUi(self, mainWidget):
        mainWidget.setObjectName("mainWidget")
        mainWidget.resize(473, 461)
        self.renameGroup = QtGui.QGroupBox(mainWidget)
        self.renameGroup.setGeometry(QtCore.QRect(10, 310, 451, 141))
        self.renameGroup.setObjectName("renameGroup")
        self.splitter = QtGui.QSplitter(self.renameGroup)
        self.splitter.setGeometry(QtCore.QRect(360, 20, 75, 101))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.renameBtn = QtGui.QPushButton(self.splitter)
        self.renameBtn.setObjectName("renameBtn")
        self.closeBtn = QtGui.QPushButton(self.splitter)
        self.closeBtn.setObjectName("closeBtn")
        self.aboutBtn = QtGui.QPushButton(self.splitter)
        self.aboutBtn.setObjectName("aboutBtn")
        self.layoutWidget = QtGui.QWidget(self.renameGroup)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 30, 145, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.startCombo = QtGui.QComboBox(self.layoutWidget)
        self.startCombo.setEditable(True)
        self.startCombo.setObjectName("startCombo")
        self.horizontalLayout_2.addWidget(self.startCombo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.countSpin = QtGui.QSpinBox(self.layoutWidget)
        self.countSpin.setMinimum(1)
        self.countSpin.setMaximum(10)
        self.countSpin.setObjectName("countSpin")
        self.horizontalLayout_4.addWidget(self.countSpin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.layoutWidget1 = QtGui.QWidget(self.renameGroup)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 161, 106))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.prefixEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.prefixEdit.setObjectName("prefixEdit")
        self.horizontalLayout_3.addWidget(self.prefixEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.postfixEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.postfixEdit.setObjectName("postfixEdit")
        self.horizontalLayout_5.addWidget(self.postfixEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.letterRadio = QtGui.QRadioButton(self.layoutWidget1)
        self.letterRadio.setObjectName("letterRadio")
        self.verticalLayout_4.addWidget(self.letterRadio)
        self.numRadio = QtGui.QRadioButton(self.layoutWidget1)
        self.numRadio.setChecked(True)
        self.numRadio.setObjectName("numRadio")
        self.verticalLayout_4.addWidget(self.numRadio)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.label = QtGui.QLabel(mainWidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 16))
        self.label.setObjectName("label")
        self.dirView = QtGui.QTreeView(mainWidget)
        self.dirView.setGeometry(QtCore.QRect(10, 40, 191, 251))
        self.dirView.setObjectName("dirView")
        self.layoutWidget2 = QtGui.QWidget(mainWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(220, 10, 241, 281))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.extCombo = QtGui.QComboBox(self.layoutWidget2)
        self.extCombo.setObjectName("extCombo")
        self.horizontalLayout.addWidget(self.extCombo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.fileListWidget = QtGui.QTableWidget(self.layoutWidget2)
        self.fileListWidget.setObjectName("fileListWidget")
        self.fileListWidget.setColumnCount(2)
        self.fileListWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.fileListWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.fileListWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.fileListWidget)

        self.retranslateUi(mainWidget)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)

    def retranslateUi(self, mainWidget):
        mainWidget.setWindowTitle(QtGui.QApplication.translate("mainWidget", "Renamer", None, QtGui.QApplication.UnicodeUTF8))
        self.renameGroup.setTitle(QtGui.QApplication.translate("mainWidget", "Rename Rules", None, QtGui.QApplication.UnicodeUTF8))
        self.renameBtn.setText(QtGui.QApplication.translate("mainWidget", "Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.closeBtn.setText(QtGui.QApplication.translate("mainWidget", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutBtn.setText(QtGui.QApplication.translate("mainWidget", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("mainWidget", "Start with:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("mainWidget", "Count:1,2,...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("mainWidget", "Prefix:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("mainWidget", "Postfix:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("mainWidget", "Using \'ABC\'", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("mainWidget", "Using \'123\'", None, QtGui.QApplication.UnicodeUTF8))
        self.letterRadio.setText(QtGui.QApplication.translate("mainWidget", "Letter", None, QtGui.QApplication.UnicodeUTF8))
        self.numRadio.setText(QtGui.QApplication.translate("mainWidget", "Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainWidget", "Choose a directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainWidget", "File ext filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.fileListWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("mainWidget", "Before", None, QtGui.QApplication.UnicodeUTF8))
        self.fileListWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("mainWidget", "After", None, QtGui.QApplication.UnicodeUTF8))

import rename_rc
